apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- prometheus/serviceaccount.yaml
- prometheus/clusterrole.yaml
- prometheus/clusterrolebinding.yaml
- prometheus/configmap.yaml
- prometheus/deployment.yaml
- prometheus/service.yaml
- node-exporter/daemonset.yaml
- node-exporter/service.yaml
- kube-state-metrics/serviceaccount.yaml
- kube-state-metrics/clusterrole.yaml
- kube-state-metrics/clusterrolebinding.yaml
- kube-state-metrics/deployment.yaml
- kube-state-metrics/service.yaml