apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana
      containers:
      - name: grafana
        image: grafana/grafana:11.5.1
        ports:
        - containerPort: 3000
          name: web
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "${GF_ADMIN_PASSWORD}"
        - name: GF_PATHS_DATA
          value: "/var/lib/grafana"
        - name: GF_PATHS_LOGS
          value: "/var/log/grafana"
        - name: GF_PATHS_PLUGINS
          value: "/var/lib/grafana/plugins"
        - name: GF_PATHS_PROVISIONING
          value: "/etc/grafana/provisioning"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-ini
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-providers
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboard-default
          mountPath: /var/lib/grafana/dashboards

        - name: grafana-dashboard-cluster
          mountPath: /var/lib/grafana/dashboards/cluster
        - name: grafana-dashboard-node
          mountPath: /var/lib/grafana/dashboards/node
        - name: grafana-dashboard-workload
          mountPath: /var/lib/grafana/dashboards/workload
        - name: grafana-dashboard-tracing
          mountPath: /var/lib/grafana/dashboards/tracing
        - name: grafana-dashboard-logging
          mountPath: /var/lib/grafana/dashboards/logging


        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsUser: 472
          runAsGroup: 472
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-ini
        configMap:
          name: grafana-ini
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-providers
        configMap:
          name: grafana-dashboards

      - name: grafana-dashboard-default
        configMap:
          name: grafana-dashboard-default

      - name: grafana-dashboard-cluster
        configMap:
          name: grafana-dashboard-cluster

      - name: grafana-dashboard-node
        configMap:
          name: grafana-dashboard-node

      - name: grafana-dashboard-workload
        configMap:
          name: grafana-dashboard-workload

      - name: grafana-dashboard-tracing
        configMap:
          name: grafana-dashboard-tracing

      - name: grafana-dashboard-logging
        configMap:
          name: grafana-dashboard-logging
