apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cpu-memory-scaledobject.yaml
- http-requests-scaledobject.yaml
- queue-length-scaledobject.yaml

labels:
- includeSelectors: true
  pairs:
    keda: "enabled"
    autoscaling: "prometheus"