apiVersion: v1
kind: Secret
metadata:
  name: prometheus-config
  namespace: monitoring
type: Opaque
stringData:
  cluster-name: "cluster1"
  environment: "dev"
  slack-webhook-url: "${SLACK_WEBHOOK_URL}"
