apiVersion: v1
kind: Secret
metadata:
  name: prometheus-web-config
  namespace: monitoring
type: Opaque
stringData:
  web-config.yml: |
    tls_server_config:
      cert_file: /etc/prometheus/certs/tls.crt
      key_file: /etc/prometheus/certs/tls.key
      min_version: "TLS12"
    basic_auth_users_file: /etc/prometheus/auth/auth
