apiVersion: v1
kind: Secret
metadata:
  name: prometheus-remote-auth
  namespace: monitoring
type: Opaque
data:
  username: "${PROMETHEUS_USERNAME_BASE64}"
  password: "${PROMETHEUS_PASSWORD_BASE64}"
