apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-server
- node-exporter
- kube-state-metrics
- pushgateway
- grafana
- opentelemetry-collector
- jaeger
# - dcgm-exporter  # Using Docker container on host instead
# - keda  # KEDA CRD가 설치되지 않은 경우 주석 처리

namespace: monitoring

labels:
- includeSelectors: true
  pairs:
    part-of: monitoring-stack
