apiVersion: v1
kind: Service
metadata:
  name: prometheus-sidecar-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 10901
    targetPort: 10901
    nodePort: 30901
    name: grpc
    protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack-prometheus
