apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thanos-vs
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: /thanos-query-frontend
      route:
        - destination:
            host: thanos-query-frontend.monitoring.svc.cluster.local
            port:
              number: 9090


