apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- node-exporter-podmonitor.yaml
- application-podmonitor.yaml

labels:
- includeSelectors: true
  pairs:
    monitoring: "enabled"