apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istiod-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - istiod-gateway
  http:
  - match:
    - port: 15012
    route:
    - destination:
        host: istiod
        port:
          number: 15012
